name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Settings:
    name: Checking and Listing XCode and githubactions Settings
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking default githubactions settings...
        uses: actions/checkout@v3
         
      # Using xcodebuild to xcode commands
      
      # Listing xcode schemes, target and anothers settings
      - name: List settings Xcode Project...
        run: xcodebuild -list -project MoviesNetwork.xcodeproj/
        
  Run-Test:
    name: Build Project and Testing 
    needs: Settings
    runs-on: macos-latest

    steps:
      #Adding xcode version
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking default githubactions settings...
        uses: actions/checkout@v3
        
      # Building xcode project
      - name: Building Xcode Project...
        run: xcodebuild -scheme MoviesNetwork -configuration "Debug" -sdk "iphonesimulator" -destination "generic/platform=iOS Simulator" SYMROOT=./builds clean build

      # Testing Unitary Tests target...
      - name: Testing Unitary Tests in Xcode Project...
        run: xcodebuild -scheme MoviesNetworkTests -configuration "Testing" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" -derivedDataPath Build/ -enableCodeCoverage YES test
        
      # Testing UI Tests target...
      - name: Testing UI Tests in Xcode Project...
        run: xcodebuild -scheme MoviesNetworkUITests -configuration "Testing" -destination "platform=iOS Simulator,name=iPhone 11,OS=latest" test
