name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking default githubactions settings...
        uses: actions/checkout@v3
         
      # Using xcodebuild to xcode commands
      
      # Listing xcode schemes, target and anothers settings
      - name: List settings Xcode Project...
        run: xcodebuild -list -project MoviesNetwork.xcodeproj/
        
      # Building xcode project
      - name: Building Xcode Project...
        run: xcodebuild -scheme MoviesNetwork -configuration "Debug" -sdk "iphonesimulator" -destination "generic/platform=iOS Simulator" SYMROOT=./builds clean build
        
      # Testing Unitary Tests target...
      - name: List settings Xcode Project...
        run: xcodebuild -scheme MoviesNetworkTests -configuration "Testing" -destination 'platform=iOS Simulator,name=iPhone 12' test
        
      # Testing UI Tests target...
      - name: List settings Xcode Project...
        run: xcodebuild -scheme MoviesNetworkUITests -configuration "Testing" -destination 'platform=iOS Simulator,name=iPhone 12' test
      
